apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: webapps  # Specify the namespace here
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2  # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: gopiadi/board123  # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # The port that the container is running on in the cluster

---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
  namespace: webapps  # Specify the namespace here
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Type of the service
